# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raracandy < Formula
  desc "CLI tool to safely edit Pokémon Gen 1 save files"
  homepage "https://github.com/abravonunez/raracandy"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abravonunez/raracandy/releases/download/v1.1.1/raracandy_Darwin_x86_64.tar.gz"
      sha256 "0772663954a5eee77389a5ec9d6beec21811753014f82010933330df53dc700c"

      def install
        bin.install "raracandy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abravonunez/raracandy/releases/download/v1.1.1/raracandy_Darwin_arm64.tar.gz"
      sha256 "f9d34184c469d9a8b15c26b6098de276f98e7e605e08d8be3c0e8059a1558142"

      def install
        bin.install "raracandy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abravonunez/raracandy/releases/download/v1.1.1/raracandy_Linux_x86_64.tar.gz"
      sha256 "af2e5805cfa293f5c0e0f5f5958d30bec1650f7568e0c02bd9fdff68d3df7e17"
      def install
        bin.install "raracandy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abravonunez/raracandy/releases/download/v1.1.1/raracandy_Linux_arm64.tar.gz"
      sha256 "12b5265f80846102039f83baf39793e4efa0180ce96a2e9af1f9161b1977ee0c"
      def install
        bin.install "raracandy"
      end
    end
  end

  test do
    system "#{bin}/raracandy --version"
  end
end
