# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raracandy < Formula
  desc "CLI tool to safely edit Pokémon Gen 1 save files"
  homepage "https://github.com/abravonunez/raracandy"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abravonunez/raracandy/releases/download/v1.2.0/raracandy_Darwin_x86_64.tar.gz"
      sha256 "c3f7a9261ca511b56c4d5c866be00d817e9dba97995905c478bb7aa86e4ab337"

      define_method(:install) do
        bin.install "raracandy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abravonunez/raracandy/releases/download/v1.2.0/raracandy_Darwin_arm64.tar.gz"
      sha256 "d47401163d83c062d61739ff4ad216253a676376d089cbec6087bda1c32584ac"

      define_method(:install) do
        bin.install "raracandy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abravonunez/raracandy/releases/download/v1.2.0/raracandy_Linux_x86_64.tar.gz"
      sha256 "0294ebfc2629b1ee9e201810aaf6c8ce29e59ed049c9eb598d44ff804eb3ffa2"
      define_method(:install) do
        bin.install "raracandy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abravonunez/raracandy/releases/download/v1.2.0/raracandy_Linux_arm64.tar.gz"
      sha256 "365b4f3ff3dc212511e14e36ebdc463e1f6f6531089de92a4e1eab1f371524ad"
      define_method(:install) do
        bin.install "raracandy"
      end
    end
  end

  test do
    system "#{bin}/raracandy --help"
  end
end
