# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sslcheckdomain < Formula
  desc "SSL certificate checker for domains with multiple output formats"
  homepage "https://github.com/abravonunez/sslcheckdomain"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abravonunez/sslcheckdomain/releases/download/v1.4.0/sslcheckdomain_Darwin_x86_64.tar.gz"
      sha256 "f6e6f0d4325b111428462acbcbb67508fd863d0a3041e794f63e5fdcf4470a27"

      define_method(:install) do
        bin.install "sslcheckdomain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abravonunez/sslcheckdomain/releases/download/v1.4.0/sslcheckdomain_Darwin_arm64.tar.gz"
      sha256 "761226aa6a38bde5a3be609ab39cbec8666d4c6af370864dc00cd6c8b4f20061"

      define_method(:install) do
        bin.install "sslcheckdomain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abravonunez/sslcheckdomain/releases/download/v1.4.0/sslcheckdomain_Linux_x86_64.tar.gz"
      sha256 "b9d126b7ce2971b5b01672825b422ef4d8a2d03488b60c3bc521a34e9b1432d5"
      define_method(:install) do
        bin.install "sslcheckdomain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abravonunez/sslcheckdomain/releases/download/v1.4.0/sslcheckdomain_Linux_arm64.tar.gz"
      sha256 "e4f3209992a179100e6a874ca5f1221e309ff036b6dfd7f4e2e1a057f97ff501"
      define_method(:install) do
        bin.install "sslcheckdomain"
      end
    end
  end

  test do
    system "#{bin}/sslcheckdomain --version"
  end
end
