# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sslcheckdomain < Formula
  desc "SSL certificate checker for domains with multiple output formats"
  homepage "https://github.com/abravonunez/sslcheckdomain"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abravonunez/sslcheckdomain/releases/download/v1.1.0/sslcheckdomain_Darwin_x86_64.tar.gz"
      sha256 "a9bc96bdbc9f0aa9b3d198fcfa217ed09ccb029260b84535f0e7553baf529f44"

      def install
        bin.install "sslcheckdomain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abravonunez/sslcheckdomain/releases/download/v1.1.0/sslcheckdomain_Darwin_arm64.tar.gz"
      sha256 "4abbf32807ff9afe959777b587abab07675d19f6c85242e0ca7e042097ccf4b8"

      def install
        bin.install "sslcheckdomain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abravonunez/sslcheckdomain/releases/download/v1.1.0/sslcheckdomain_Linux_x86_64.tar.gz"
      sha256 "4d9ea0d63931f05fbcc88b0b57a366054b58b38fd5fc6a4f92d03664ef7a4bd2"
      def install
        bin.install "sslcheckdomain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abravonunez/sslcheckdomain/releases/download/v1.1.0/sslcheckdomain_Linux_arm64.tar.gz"
      sha256 "079a63279acf240daa3be80abe82c87be539e92955a3d0ae4d2eb7b7bd543690"
      def install
        bin.install "sslcheckdomain"
      end
    end
  end

  test do
    system "#{bin}/sslcheckdomain --version"
  end
end
